services:
  db:
    image: mysql:8.0
    container_name: profile-blog-db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: profile_blog
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

  api:
    build: ./ServerSide
    container_name: go-api
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./ClientSide:/api/static
      - ./ServerSide:/api
    ports:
      - "8080:8080"
    environment:
      DB_USER: root
      DB_PASSWORD: password
      DB_NAME: profile_blog
      DB_HOST: db

volumes:
  db_data: